###
< {%
    request.variables.set("token", "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI3OTU5OTIxYi0xOTBmLTQ0NjAtODk4ZC01N2I4YTU5OTVhMmQiLCJlbWFpbCI6ImJsb2RAYmsucnUiLCJuYW1lIjoic3RyaW5nIHN0cmluZyIsInBlcm1pc3Npb25zIjpbIlJlYWRNZW1iZXIiLCJVcGRhdGVNZW1iZXIiXSwiZXhwIjoxNjk3MTg5MjkzLCJpc3MiOiJSZWZlcmVuZHVtIiwiYXVkIjoicmVmZXJlbmR1bS5nZSJ9.jxij9wgDv9te4uyOQsrmy5ObXgpMpWfcsLBse6LTj4g")
%}
POST https://localhost:7059/api/{{version}}/question/Seed
Authorization: Bearer {{token}}



###
< {%
    request.variables.set("token",
        "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhNDU3OWFhMS0yYmQzLTQ4YWItODFkYi00MzY4YjI1MzJmZjMiLCJlbWFpbCI6InZtQHZtLmNvbSIsIm5hbWUiOiJzdHJpbmcgc3RyaW5nIiwicGVybWlzc2lvbnMiOlsiUmVhZE1lbWJlciIsIlVwZGF0ZU1lbWJlciJdLCJleHAiOjE2ODc4NTEzNjAsImlzcyI6IlJlZmVyZW5kdW0iLCJhdWQiOiJyZWZlcmVuZHVtLmdlIn0.Eo2fMgrXz9iF8nc3xjdAbDy0MzjmBC9vHF2VhU3YONo")
%}
GET https://localhost:7059/api/{{version}}/Question/
Authorization: Bearer {{token}}



