name: Publish 

on:
  workflow_dispatch:
  push:
    branches:
    - Master

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore
        run: dotnet restore ./src/vm.referendum.Api/vm.referendum.Api.csproj

      - name: Build
        run: dotnet build ./src/vm.referendum.Api/vm.referendum.Api.sln --configuration Release --no-restore

      - name: Publish
        run: dotnet publish ./src/vm.referendum.Api/vm.referendum.Api.sln --configuration Release --no-build --output ./publish
